In [ ]:
#Aula 02 - Python
#Dados numéricos

In [1]:
a = 1
print('Valor de a = '+str(a))
type(a)

Valor de a = 1


int

In [2]:
b = 1.0
print(b)
type(b)

1.0


float

In [3]:
c = int(b)
print(c)
type(c)

1


int

In [5]:
# Declarando nan 
import numpy as np
d = np.nan
print(d)
type(d)

nan


float

In [6]:
#Operação com NaN
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)

nan
nan
1.0


In [7]:
# Declaração de variável texto 
f = 'Fábio'
g = "Gabriel"
print(f)
print(g)
print(f+g)
print(f+' '+g)

Fábio
Gabriel
FábioGabriel
Fábio Gabriel


In [ ]:
#Dados tipo bool - lógica

In [8]:
a == 1

True

In [9]:
h = (a==1)
print(h)
type(h)

True


bool

In [10]:
h = (a==2)
print(h)
type(h)

False


bool

In [11]:
i = True
type(i)

bool

In [12]:
ii = 'True'
type(ii)

str

In [13]:
#Operação de comparação
a==b

True

In [14]:
a>b

False

In [15]:
a!=b

False

In [16]:
a>=b

True

In [17]:
#Operações matemáticas
a+b

2.0

In [18]:
ab = a+b
print(ab)

2.0


In [19]:
l = a*b # Não use l como variável
print("Não use l como nome de variável")
j = a*b
print(j)

Não use l como nome de variável
1.0


In [20]:
a/b

1.0

In [21]:
5**2

25

In [22]:
import math

math.exp(10)

22026.465794806718

In [23]:
math.exp(0)

1.0

In [24]:
math.exp(a)

2.718281828459045

In [25]:
math.exp(-10)

4.5399929762484854e-05

In [26]:
import math as mt
mt.log(c)

0.0

In [27]:

mt.log10(100)

2.0

In [28]:
myFirstList = [1,2,3]
print(myFirstList)

[1, 2, 3]


In [29]:
print(myFirstList[0])
print(myFirstList[2])

1
3


In [30]:

myFirstList==a

False

In [31]:
mySecList = [1,a,'c']
print(mySecList)

[1, 1, 'c']


In [32]:

type(mySecList)

list

In [33]:
type(mySecList[2])

str

In [35]:
type(mySecList[1])

int

In [36]:
path = r"C:\Users\PC\Documents\GitHub\ENS5173_202401"
print(path)

C:\Users\Leonardo.Hoinaski\Documents\ENS410064_1


In [39]:
path = r"C:\Users\PC\Documents\GitHub\ENS5173_202401"
print(path)

C:\Users\PC\Documents\GitHub\ENS5173_202401


In [40]:
import os
os.listdir(path)

['.git', '.gitignore', 'README.md', 'Scripts', 'Untitled.ipynb', 'venv']

In [41]:
os.listdir(path)[0]


'.git'

In [42]:
path+"/"+os.listdir(path)[0]

'C:\\Users\\PC\\Documents\\GitHub\\ENS5173_202401/.git'

In [43]:
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [44]:
os.getcwd()

'C:\\Users\\PC\\venv\\Scripts'

In [45]:
os.chdir('C:\\Users\\PC\\Documents\\')

In [46]:
os.getcwd()

'C:\\Users\\PC\\Documents'

In [47]:
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)

Criando diretório C:\Users\PC\Documents/test


In [48]:
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")

Criando diretório C:\Users\PC\Documents/test2


In [49]:
import numpy as np
n = np.array(0)
type(n)

numpy.ndarray

In [50]:
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList)
print(n)

[ 1  2  3 10 20 55]


In [51]:
n = np.random.rand(10,10)
print(n)
print(n.shape)


[[4.13126680e-01 9.52253081e-01 2.29723251e-01 9.60260466e-01
  2.94263615e-01 6.53372641e-01 8.59610857e-01 1.34836474e-01
  4.73869160e-01 5.10226424e-01]
 [7.53101396e-01 6.23716665e-01 2.59638852e-01 4.89572893e-01
  1.48184162e-01 3.01545069e-01 8.42080320e-01 1.02265213e-02
  7.50410950e-01 7.79711525e-01]
 [8.82501853e-02 3.55047712e-01 3.39244209e-01 2.59716292e-01
  3.81198301e-01 5.93916146e-01 6.01172737e-01 9.18544145e-01
  1.48941275e-01 2.67027650e-02]
 [4.50315138e-01 9.98213041e-01 9.36592151e-01 5.36901837e-01
  4.00209224e-01 4.42503946e-01 5.86294188e-01 9.64008121e-01
  1.35695688e-01 7.66117015e-01]
 [4.51258718e-02 8.31026955e-01 9.12336135e-01 6.77530524e-01
  2.49284807e-01 5.77805156e-01 7.00622429e-01 7.70246708e-01
  5.47385322e-01 3.80274645e-01]
 [5.08323479e-02 5.24106480e-01 2.25403996e-01 3.44849996e-01
  3.65651145e-01 1.81516547e-01 5.44065583e-02 8.80780231e-01
  3.70464676e-01 9.31410422e-01]
 [4.45499969e-01 9.24944415e-04 3.79062273e-01 7.54469889e

In [52]:
n[0,:]

array([0.41312668, 0.95225308, 0.22972325, 0.96026047, 0.29426362,
       0.65337264, 0.85961086, 0.13483647, 0.47386916, 0.51022642])

In [53]:

n[:,0]

array([0.41312668, 0.7531014 , 0.08825019, 0.45031514, 0.04512587,
       0.05083235, 0.44549997, 0.33670671, 0.29502993, 0.77292872])

In [56]:
n[:,1:5]

array([[9.52253081e-01, 2.29723251e-01, 9.60260466e-01, 2.94263615e-01],
       [6.23716665e-01, 2.59638852e-01, 4.89572893e-01, 1.48184162e-01],
       [3.55047712e-01, 3.39244209e-01, 2.59716292e-01, 3.81198301e-01],
       [9.98213041e-01, 9.36592151e-01, 5.36901837e-01, 4.00209224e-01],
       [8.31026955e-01, 9.12336135e-01, 6.77530524e-01, 2.49284807e-01],
       [5.24106480e-01, 2.25403996e-01, 3.44849996e-01, 3.65651145e-01],
       [9.24944415e-04, 3.79062273e-01, 7.54469889e-01, 5.72742369e-01],
       [7.32976419e-01, 3.43346201e-01, 2.66124184e-01, 2.03862842e-01],
       [6.49994408e-01, 1.21561096e-01, 7.97693651e-01, 4.15712759e-01],
       [7.65771033e-01, 6.97164177e-01, 5.92474388e-01, 9.93342169e-01]])

In [58]:
n[0,1:5]

array([0.95225308, 0.22972325, 0.96026047, 0.29426362])

In [59]:
n[0,-1]

0.5102264239763293

In [60]:

n[0,4:-1]

array([0.29426362, 0.65337264, 0.85961086, 0.13483647, 0.47386916])

In [61]:
n[0,4:]

array([0.29426362, 0.65337264, 0.85961086, 0.13483647, 0.47386916,
       0.51022642])

In [62]:
an = np.log(n*5)
print(an)

[[ 0.72543691  1.56051347  0.13855796  1.5688872   0.38615865  1.18383026
   1.45816243 -0.39425463  0.86261388  0.93653723]
 [ 1.32588251  1.13737884  0.26097427  0.895216   -0.29986153  0.41060212
   1.43755803 -2.9733329   1.32230362  1.36060664]
 [-0.81814157  0.57393481  0.52840286  0.26127248  0.64500235  1.08842077
   1.10056494  1.5244726  -0.29476527 -2.01355025]
 [ 0.81163028  1.60764936  1.54393055  0.98749791  0.6936701   0.79413202
   1.07550432  1.57278235 -0.38790258  1.34301755]
 [-1.48886163  1.42434486  1.51769112  1.22013724  0.22027868  1.06091935
   1.25365176  1.3483935   1.00683562  0.64257637]
 [-1.36978445  0.9633775   0.11957696  0.54479216  0.60336236 -0.09697055
  -1.30183266  1.48249077  0.61644073  1.53838265]
 [ 0.80087981 -5.376339    0.63938313  1.327698    1.05211863  1.49538629
   1.16289646  0.11352802  0.69172524 -0.22762116]
 [ 0.52089489  1.29879616  0.5404219   0.28564569  0.01913006  1.18245214
  -0.03693332 -2.54014259  1.45868684  1.1461371 ]
